# Generated by Django 6.0.6 on 2026-08-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('state_name', models.CharField(db_index=True, max_length=100)),
                ('state_code', models.IntegerField(blank=True, null=True)),
                ('district_name', models.CharField(db_index=True, max_length=100)),
                ('district_code', models.IntegerField(blank=True, null=True)),
                ('block_name', models.CharField(db_index=True, max_length=100)),
                ('block_code', models.IntegerField(blank=True, null=True)),
                ('village_name', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('village_code', models.IntegerField(blank=True, null=True)),
                ('nutrient_type', models.CharField(blank=True, max_length=50, null=True)),
                ('nutrient_name', models.CharField(db_index=True, max_length=100)),
                ('nutrient_level', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Soil Database Record',
                'verbose_name_plural': 'Soil Database Records',
                'db_table': 'soil_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Cereal', 'Cereal'), ('Pulse', 'Pulse'), ('Oilseed', 'Oilseed'), ('Cash Crop', 'Cash Crop'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit')], max_length=50)),
                ('target_yield_tonnes_per_ha', models.DecimalField(decimal_places=2, default=4.5, max_digits=5)),
                ('nitrogen_demand_kg_per_ha', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phosphorus_demand_kg_per_ha', models.DecimalField(decimal_places=2, max_digits=6)),
                ('potassium_demand_kg_per_ha', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ideal_ph_min', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('ideal_ph_max', models.DecimalField(decimal_places=2, default=7.5, max_digits=4)),
                ('growth_duration_days', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('state_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('block_name', models.CharField(blank=True, max_length=100, null=True)),
                ('village_name', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('form_factor', models.CharField(choices=[('Granular', 'Granular'), ('Liquid', 'Liquid / Foliar'), ('Water Soluble', '100% Water Soluble')], default='Granular', max_length=30)),
                ('n_content_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('p_content_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('k_content_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sulphur_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('zinc_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('price_per_bag_inr', models.DecimalField(decimal_places=2, default=300.0, max_digits=8)),
                ('bag_weight_kg', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(decimal_places=2, help_text='Field area in hectares', max_digits=7)),
                ('soil_type', models.CharField(blank=True, max_length=80, null=True)),
                ('irrigation_type', models.CharField(choices=[('Rainfed', 'Rainfed'), ('Drip', 'Drip Irrigation'), ('Sprinkler', 'Sprinkler Irrigation'), ('Canal / Borewell', 'Flood / Surface Irrigation')], default='Canal / Borewell', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='fertilizer_app.farm')),
            ],
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(auto_now_add=True)),
                ('nitrogen', models.DecimalField(decimal_places=2, help_text='Available N in kg/ha', max_digits=7)),
                ('phosphorus', models.DecimalField(decimal_places=2, help_text='Available P in kg/ha', max_digits=7)),
                ('potassium', models.DecimalField(decimal_places=2, help_text='Available K in kg/ha', max_digits=7)),
                ('soil_ph', models.DecimalField(decimal_places=2, help_text='Soil pH (1-14)', max_digits=4)),
                ('organic_carbon_pct', models.DecimalField(decimal_places=2, help_text='Organic Carbon %', max_digits=5)),
                ('electrical_conductivity', models.DecimalField(decimal_places=2, default=0.45, help_text='EC (dS/m)', max_digits=5)),
                ('zinc', models.DecimalField(decimal_places=2, default=0.8, help_text='Zinc ppm', max_digits=5)),
                ('boron', models.DecimalField(decimal_places=2, default=0.5, help_text='Boron ppm', max_digits=5)),
                ('sulphur', models.DecimalField(decimal_places=2, default=12.0, help_text='Sulphur ppm', max_digits=5)),
                ('iron', models.DecimalField(decimal_places=2, default=6.0, help_text='Iron ppm', max_digits=5)),
                ('source', models.CharField(default='Lab Test', max_length=80)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_tests', to='fertilizer_app.field')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall_forecast_mm', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('wind_speed_kmh', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='fertilizer_app.field')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_fertilizer', models.CharField(max_length=200)),
                ('total_quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_cost_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_schedule', models.JSONField(default=list)),
                ('ai_confidence', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('ai_alternatives', models.JSONField(default=list)),
                ('ph_amendment', models.CharField(blank=True, max_length=250, null=True)),
                ('micronutrient_advice', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_app.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_app.field')),
                ('soil_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fertilizer_app.soiltest')),
                ('weather_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fertilizer_app.weatherrecord')),
            ],
        ),
    ]
